config/routes.rb
Rails.application.routes.draw do

  get 'rental/index'

  get 'rental/show/:id' => 'rental#show', :as => 'rental_show'

  devise_for :users
  resources :movies do
    get 'page/:page', :action => :index, :on => :collection
  end

  get 'people/index'

  get 'home' => 'page#home'
  get 'about_us' => 'page#about_us'

  match 'contact_us' => 'page#contact_us', :via => [:post, :get]

  get 'products' => 'page#products'
  get 'newsletter' => 'page#newsletter'
  get 'blog' => 'page#blog'
  get 'calendar(/:year(/:month))' => "page#calendar", :as => 'calendar'
  get 'articles' => 'page#articles'
  get 'login' => 'page#login'

  get 'dave/teach'
  get 'dave/speak'
  get 'dave/dig'

  get 'say/hello' #=> 'say#hello'
  get 'say/goodbye'
  get 'say/something'

  root 'page#home'

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  validates_presence_of :name, :director
  validates_numericality_of :year, :length, :greater_than => 0
  validates_uniqueness_of :name, :message => "Already used!"
  validates_length_of :format, :maximum => 5, :minimum => 2

  paginates_per 5

  def propername
    name.titleize
  end
end

app/models/people.rb
class People < ActiveRecord::Base

  def fullname
    return "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    first_name + " " + last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dave_controller.rb
class DaveController < ApplicationController
  def teach
  end

  def speak
  end

  def dig
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, except: [ :index, :show ]

  # GET /movies
  # GET /movies.json
  def index
  #  @prev_page = @page - 1 unless @page == 0
  #  @next_page = @page + 1 unless (@page * 5 >= Movie.count)
  #  @movies = Movie.limit(5).offset(@page * 5).order(:updated_at => :desc)
    @movies = Movie.page(@page).order(:updated_at => :desc)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def authenticate
      authenticate_user! && current_user.try(:admin?)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :director, :description, :year, :length, :format, :image, :thumbnail)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about_us
  end

  def contact_us
    @submitted = params["commit"]
    @name = params["name"]
    @form_error = false
    if @name == ""
      flash.now['error'] = "Please enter your name! "
      @form_error = true
    end
    @email = params["email"]
    @question = params["question"]
    @newsletter = params["newsletter"] == "newsletter"
    gender = params["gender"]
    @male = gender == "Male" #true or false
    @female = gender == "Female" #true or false
    @product = params["product"]
  end

  def products
  end

  def newsletter
  end

  def blog
  end

  def calendar
    @time = Time.now
    @month = @time.month
    @year = @time.year
    @day = @time.day
    @day_of_week = @time.strftime(" %w ").to_i
  end

  def articles
  end

  def login
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = People.all
  end
end

app/controllers/rental_controller.rb
class RentalController < ApplicationController
  def index
    @movies = Movie.page(@page).order(:updated_at => :desc)
  end

  def show
    @movie = Movie.find( params['id'])
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @now = Time.now
    @yo = "Yo Ho!"
  end

  def goodbye
  end

  def something
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link_to(click_text, action, url, style)
    if action_name == action
      return link_to click_text, url, :class => style
    else
      return link_to click_text, url
    end
  end
end

app/helpers/dave_helper.rb
module DaveHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/page_helper.rb
module PageHelper
  def calendar(month, year, day)
    current_date = Date.new(year, month, @day)
    cal = current_date.strftime("%B")
    cal += link_to "Prev", "/page/calendar?month=#{month-1}&year=#{year}"
    cal += "<table border='1'>\n\t<tr>\n"
    days = %w(Sun Mon Tue Wed Thu Fri Sat)
    days.each do |day|
      cal += "\t<td>#{day}</td>\n"
    end
    # First week of the month
    cal += "<tr>"
    @day_of_week.times do |day|
    cal += "<td>&nbsp;</tdr>"
    end
    #Print calendar
    (7 - @day_of_week).times do |day|
    cal += "<td>#{day +1}</td>"
    end
    cal += "</tr>"
    cal += "\t</tr>\n</table>\n"
    cal += "Month: #{month}<br/>Year: #{year}<br/>"
    cal += "Date: #{current_date}<br/"
    return cal
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/rental_helper.rb
module RentalHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/dave/dig.html.erb
<h1>Dave#dig</h1>
<p>Find me in app/views/dave/dig.html.erb</p>

app/views/dave/speak.html.erb
<h1>Dave#speak</h1>
<p>Find me in app/views/dave/speak.html.erb</p>

app/views/dave/teach.html.erb
<h1>Dave#teach</h1>
<p>Find me in app/views/dave/teach.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Lecture</title>
  <%= stylesheet_link_tag    'application', media: 'screen', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
<div id="wrapper"><!-- #wrapper -->

	<header><!-- header -->
		<h1><a href="#">Low Beskids</a></h1>
		<h2>Same yesterday and today</h2>
    <%= image_tag "cowboyup.jpg", size: "940x200", alt: "Daves a Cowboy" %>
		<!--<img src="images/cowboyup.jpg" width="940" height="200" alt=""><!-- header image -->
	</header><!-- end of header -->

<%= render :partial => 'shared/nav' %>

	<section id="main"><!-- #main content and sidebar area -->
		<section id="container"><!-- #container -->
			<section id="content"><!-- #content -->

<%= yield %>

</section><!-- end of #content -->
		</section><!-- end of #container -->

		<aside id="sidebar"><!-- sidebar -->
				<h3>Things To Do</h3>
					<ul>
						<li><a href="#">Play Games</a></li>
						<li><a href="#">Chat With Friends</a></li>
						<li><a href="#">Swap Stories</a></li>
						<li><a href="#">Sell Stuff</a></li>
						<li><a href="#">Buy Stuff</a></li>
						<li><a href="#">Trade Stuff</a></li>
					</ul>

				<h3>Our Sponsors</h3>
				<%= image_tag "ad125.jpg" %> <%= image_tag "ad125.jpg" %><br/>
				<%= image_tag "ad125.jpg" %> <%= image_tag "ad125.jpg" %><br/><br/>

				<h3>Connect With Us</h3>
					<ul>
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Facebook</a></li>
					</ul>

		</aside><!-- end of sidebar -->

	</section><!-- end of #main content and sidebar-->

	<footer>
		<section id="footer-area">

			<section id="footer-outer-block">
					<aside id="first" class="footer-segment">
							<h3>Blogroll</h3>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
									<li><a href="#">four linkylinks</a></li>
									<li><a href="#">five linkylinks</a></li>
								</ul>
					</aside><!-- end of #first footer segment -->

					<aside id="second" class="footer-segment">
							<h3>Awesome Stuff</h3>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
									<li><a href="#">four linkylinks</a></li>
									<li><a href="#">five linkylinks</a></li>
								</ul>
					</aside><!-- end of #second footer segment -->

					<aside id="third" class="footer-segment">
							<h3>Coolness</h3>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
									<li><a href="#">four linkylinks</a></li>
									<li><a href="#">five linkylinks</a></li>
								</ul>
					</aside><!-- end of #third footer segment -->

					<aside id="fourth" class="footer-segment">
							<h3>Blahdyblah</h3>
								<p>Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.</p>
					</aside><!-- end of #fourth footer segment -->

			</section><!-- end of #footer-outer-block -->

		</section><!-- end of #footer-area -->
	</footer>

</div><!-- #wrapper -->
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.text_field :length %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :thumbnail %><br>
    <%= f.text_field :thumbnail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<%= paginate @movies %>
<%#= link_to "Prev", movies_path(page: @prev_page) %>
<%#= link_to "Next", movies_path(page: @next_page) %>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Director</th>
      <th>Description</th>
      <th>Year</th>
      <th>Length</th>
      <th>Format</th>
      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.id %></td>
        <td><%= link_to movie.propername, movie_path(movie) %></td>
        <td><%= movie.director %></td>
        <td><%= truncate(movie.description.html_safe, length: 20 ) %></td>
        <td><%= movie.year %></td>
        <td><%= movie.length %></td>
        <td><%= movie.format %></td>
        <td><%= link_to( image_tag(movie.thumbnail), movie ) %></td>
        <td><%= link_to 'Show', movie %></td>
        <% if current_user.try(:admin?) %>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.propername %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Length:</strong>
  <%= @movie.length %>
</p>

<p>
  <strong>Format:</strong>
  <%= @movie.format %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @movie.image %>
</p>

<p>
  <strong>thumbnail:</strong>
  <%= image_tag @movie.image %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/page/about_us.html.erb
<h1>Page#about_us</h1>
<p>Find me in app/views/page/about_us.html.erb</p>

app/views/page/articles.html.erb
<h1>Page#articles</h1>
<p>Find me in app/views/page/articles.html.erb</p>

app/views/page/blog.html.erb
<h1>Page#blog</h1>
<p>Find me in app/views/page/blog.html.erb</p>

app/views/page/calendar.html.erb
<h1>Calendar</h1>
<!--
<%= mail_to "la@gmail.com", "Email Me", encode: "hex" %><br/>
# Day of the week <%= @day_of_week %><br/>
Date: <%= @time.year %> <%= @time.strftime("%B") %> -->


<%= calendar(@month, @year, @day).html_safe %>

app/views/page/contact_us.html.erb
<h1>Contact_us</h1>

<!-- <pre>  Debugging code
<%= params.each do |key, value| %>
<%= key + ":" + value  %>
<% end %>
</pre> -->
Your name is : <%= @name %><br/>
Your email is : <%= @email %><br/>

<% if flash['error'] %>
    <div class='error'><%= flash['error'] %></div>
<% end %>

<% if !@submitted || @form_error %>
  <br/>
  <%= form_for contact_us_path, :method => "POST" do %>
    <%= label_tag :name, "Enter your Name: " %>
    <%= text_field_tag :name, @name, autofocus: "autofocus", placeholder: "Enter your name here" %><br/>
    <%= label_tag :email, "Enter your email: " %>
    <%= email_field_tag :email, @email, placeholder: "someone@domain.com"  %><br/>
    <%= label_tag :question, "Enter the question" %><br/>
    <%= text_area_tag :question, @question, size: "40x10" %><br/>
    <%= check_box_tag :newsletter, 'newsletter', @newsletter %>
    Subscribe to my newsletter?
    <br/>
    Male  <%= radio_button_tag :gender, "Male", @male %> Female
    <%= radio_button_tag :gender, "Female", @female %><br/>

    <%= select_tag :product, options_for_select( [
                         ['Skis', 0],
                         ['Poles', 1],
                       ['Boots', 2] ], @product) %>

    <br/>
    <%= submit_tag "Ask Question" %>
  <% end %>
<% else %>
  Thanks for your information
<% end %>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/page/login.html.erb
<h1>Page#login</h1>
<p>Find me in app/views/page/login.html.erb</p>

app/views/page/newsletter.html.erb
<h1>Page#newsletter</h1>
<p>Find me in app/views/page/newsletter.html.erb</p>

app/views/page/products.html.erb
<h1>Page#products</h1>
<p>Find me in app/views/page/products.html.erb</p>

app/views/people/index.html.erb
<h1>People#index</h1>

<%= @people.each do | person | %>
  <%= person.fullname %><br/>
<% end %>

app/views/rental/index.html.erb
<h1>Listing movies</h1>

<%= paginate @movies %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Director</th>
      <th>Description</th>
      <th>Year</th>
      <th>Length</th>
      <th>Format</th>
      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.propername, rental_show_path( movie.id ) %></td>
        <td><%= movie.director %></td>
        <td><%= truncate(movie.description.html_safe, length: 20 ) %></td>
        <td><%= movie.year %></td>
        <td><%= movie.length %></td>
        <td><%= movie.format %></td>
        <td><%= link_to( image_tag(movie.thumbnail), movie ) %></td>
        <td><%= link_to 'Show', rental_show_path( movie.id ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/rental/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.propername %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Length:</strong>
  <%= @movie.length %>
</p>

<p>
  <strong>Format:</strong>
  <%= @movie.format %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @movie.image %>
</p>

<p>
  <strong>thumbnail:</strong>
  <%= image_tag @movie.image %>
</p>

<%= link_to 'Back', rental_index_path %>

app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<h2>goodbye Dave</h2>

app/views/say/hello.html.erb
<h1>Say#hello</h1><%= @now %>
<p>Find me in app/views/say/hello.html.erb</p>

Hello Dave.<br>


<%= 2+2 %>
<% 3.times do %>
 <p>Hi!</p>
    Ho!
    <script>document.write("hello!");</script>
    <%#= @yo %>
<% end %>
<br/>
<div class="dave">
<%= link_to "Dave teach", dave_teach_path %>
</div>

app/views/say/something.html.erb
<h1>say#something</h1>
something to say

app/views/shared/_nav.html.erb
<nav><!-- top nav -->
  <div class="menu">
    <ul>
      <li>
        <%= nav_link_to "Home", "home", home_path, 'current_page' %>
      </li>
      <li><%= link_to "About", about_us_path %>
        <ul>
           <li><%= link_to "Contact Us", contact_us_path %></li>
         </ul>
      </li>
      <li><%= link_to "Products", products_path %></li>
      <li><%= link_to "Calendar", calendar_path %></li>
      <li><%= link_to "Articles", articles_path %>
        <ul>
          <li><%= link_to "Newsletter", newsletter_path %></li>
        </ul>
      </li>
      <li><%= link_to "Blog", blog_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav><!-- end of top nav -->
<% if user_signed_in? %>
  Welcome! <%= current_user.full_name.titleize %>
<% end %>